// <auto-generated />
using System;
using DatasInformation.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatasInformation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217100201_Third")]
    partial class Third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatasInformation.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "All about tech and gadgets",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Health tips and news",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Travel guides and experiences",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Recipes and food reviews",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sports news and events",
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("DatasInformation.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Great article! Learned a lot about tech.",
                            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Very helpful health tips, thanks!",
                            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Content = "I want to visit these places ASAP!",
                            CreatedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            UserName = "Charlie"
                        });
                });

            modelBuilder.Entity("DatasInformation.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FeatureImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Theon",
                            CategoryId = 1,
                            Content = "Stay updated with the latest technology trends for 2025.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Latest Tech Trends 2025"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Ramsay",
                            CategoryId = 2,
                            Content = "Learn how to eat healthy and maintain your lifestyle.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Healthy Eating Tips"
                        },
                        new
                        {
                            Id = 3,
                            Author = "lockhead",
                            CategoryId = 3,
                            Content = "Check out the most amazing travel destinations this year.",
                            PublishedDate = new DateTime(2025, 12, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Travel Destinations"
                        });
                });

            modelBuilder.Entity("DatasInformation.Models.Comment", b =>
                {
                    b.HasOne("DatasInformation.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DatasInformation.Models.Post", b =>
                {
                    b.HasOne("DatasInformation.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DatasInformation.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("DatasInformation.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
